version: "3"
services:
  springboot:
    image: mohamed224/springboot-mongo-app:1.0.0
    container_name: springboot-mongodb-app
    restart: always
    ports:
      - 8083:8080
    environment:
       MONGO_HOST : mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
