
name: springboot-mongodb CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: mohamed224/springboot-mongo-app
        tags: latest
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
  deploy:
    name: Run docker container
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: run docker container using docker-compose
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        
          docker run --name mongodb -p 27017:27017 -d mongo:latest
          docker run --name springboot-mongo-app -p 8082:8080 --link mongodb -e MONGO_HOST=mongodb -d ${{ secrets.DOCKER_USERNAME }}/springboot-mongo-app:latest
          
       
         
        
