version: "3"
services:
  springboot:
    image: springboot-mongo-app:latest
    container_name: springboot-mongodb-app
    restart: always
    ports:
      - 8080:8080
    environment:
       MONGO_HOST : mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - 27017:27017
